# constroi container com wordpress mysl e phpmyadmin
version: '2'
services:
  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mysql
    links:
      - mysql 
    volumes:
      - ./html:/var/www/html       
    ports:
      - 8080:80
      #- 127.0.0.1:80:80 # versão com ip
    environment:
     - WORDPRESS_DB_HOST=mysql
     - WORDPRESS_DB_NAME=wordpress
     - WORDPRESS_DB_USER=root
     - WORDPRESS_DB_PASSWORD=123

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data/db/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123           
      - MYSQL_USER=root      
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=wordpress
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    links:
      - mysql   
    restart: always
    ports:
      - '8081:80'
    environment:      
      #- PMA_ARBITRARY=1 # pede servidor para se conectar, colocar ip que e gerado pelo docker toobox 
      - PMA_HOST=mysql 